
steps:
  - label: ":pipeline: Converge build steps"
    agents: &agentConfig
      "gcp:project-id": "cookies-co"
    plugins:
      - chronotc/monorepo-diff#v2.0.4:
          diff: "git diff --name-only HEAD~1"
          watch:
            - path: app/backend
              config:
                label: ":buildkite: Build/Test Backend"
                command: "buildkite-agent pipeline upload infra/devops/backend.build.yml"
                agents: *agentConfig
            - path: app/frontend
              config:
                label: ":buildkite: Build/Test Frontend"
                command: "buildkite-agent pipeline upload infra/devops/frontend.build.yml"
                agents: *agentConfig
