apiVersion: v1
kind: Service
metadata:
  name: sample-ext
  labels:
    app: sample
    role: server
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sandbox.echo.cloud.cookies.co
spec:
  ports:
    - name: tls
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: sample
    role: server
  type: LoadBalancer
  publishNotReadyAddresses: yes
