apiVersion: v1
kind: Service
metadata:
  name: sample
  labels:
    app: sample
    role: server
    version: '%{app_version}'
    revision: '%{server_revision}'
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"443": {}}}'
    cloud.google.com/app-protocols: '{"http": "HTTP2", "tls": "HTTP2"}'
spec:
  ports:
    - name: tls
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: sample
    role: server
    version: '%{app_version}'
    revision: '%{server_revision}'
  type: NodePort
  publishNotReadyAddresses: yes
