apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/app-protocols: '{"http": "HTTP2", "tls": "HTTP2"}'
    cloud.google.com/neg: '{"exposed_ports": {"443": {}}}'
  labels:
    app: sample
    revision: v20210830-170d1ea
    role: server
    version: v1a
  name: sample
spec:
  ports:
  - name: tls
    port: 443
    protocol: TCP
    targetPort: 8443
  publishNotReadyAddresses: true
  selector:
    app: sample
    revision: v20210830-170d1ea
    role: server
    version: v1a
  type: NodePort
